# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql_fields.fields.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examples', django_mysql_fields.fields.jsonfield.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='one_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6a21\u5757\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='two_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6a21\u5757\u5b50\u9879')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.one_model')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='zixiang_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.two_model'),
        ),
    ]
